<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ps1</string>
		<string>PS1</string>
	</array>
	<key>name</key>
	<string>PowerShell</string>
	<key>foldingStartMarker</key>
	<string>(\{\s*(#.*)?$)</string>
	<key>foldingStopMarker</key>
	<string>^\s*(\})</string>	
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(?i:if|else|elseif|switch|while|default|for|do|until|break|continue|foreach|return|filter|in|trap|throw|param|begin|process|end|function|global|local|private|script|contained)\b</string>
			<key>name</key>
			<string>keyword.control.powershell</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:\w+-\w+)\b</string>
			<key>name</key>
			<string>support.function.powershell</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s+-(?i:eq|ne|ge|gt|lt|le|like|notlike|match|notmatch|replace|contains|notcontains|ieq|ine|ige|igt|ile|ilt|ilike|inotlike|imatch|inotmatch|ireplace|icontains|inotcontains|ceq|cne|cge|cgt|clt|cle|clike|cnotlike|cmatch|cnotmatch|creplace|ccontains|cnotcontains|is|isnot|as|and|or|band|bor|not|f)\b</string>
			<key>name</key>
			<string>keyword.operator.powershell</string>
		</dict>	
		<dict>
			<key>begin</key>
			<string>#</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.powershell</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.powershell</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.powershell</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.powershell</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.powershell</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.powershell</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.powershell</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.powershell</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>@"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.powershell</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"@</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.powershell</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.region.powershell</string>
		</dict>				
		<dict>
			<key>match</key>
			<string>(\$)[a-zA-Z_][a-zA-Z0-9_]*</string>
			<key>name</key>
			<string>variable.other.powershell</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.powershell</string>
	<key>uuid</key>
	<string>B70C41F7-B5D0-3327-B3AC-0B1A44D56CD1</string>
</dict>
</plist>
